/*
 * rdata.c - DOS data-segment (dseg) definitions for the faithful renderer port.
 *
 * Every initialized value below is transcribed from the disassembled original
 * data segment: reference/restunts/src/restunts/asm/dseg.asm (dseg base
 * linear address 0x3B770).  Zero-initialized state variables are sized from
 * the same file.  Duplicated tables were cross-checked against
 * reference/restunts/src/restunts/sdl/main.cpp and sdl/data3d.cpp.
 *
 * The TRACKOBJECT tables and off_3BE44 are generated by
 * tools/extract_dseg_tables.py (reproducible transcription; do not hand-edit).
 *
 * C types follow the extern declarations in frame.c / shape3d.c / math.c /
 * externs.h (Watcom 16-bit mapping: db=char/uint8_t, dw=int16_t/uint16_t,
 * dd=int32_t or pointer).  `far` is #defined empty by rport.h/externs.h.
 */
#include "rfbsize.h"
#include "externs.h"
#include "shape3d.h"
#include "shape2d.h"
#include "math.h"

/* Layout sanity: the DOS structs that contain no pointers must keep their
 * exact 16-bit packed sizes in this port. */
_Static_assert(sizeof(struct RECTANGLE) == 8, "RECTANGLE packed size");
_Static_assert(sizeof(struct VECTOR) == 6, "VECTOR packed size");
_Static_assert(sizeof(struct MATRIX) == 18, "MATRIX packed size");
_Static_assert(sizeof(struct GAMEINFO) == 26, "GAMEINFO packed size");
_Static_assert(sizeof(struct GAMESTATE) == 1120, "GAMESTATE packed size");

/* ------------------------------------------------------------------ */
/* Group 3 (subset needed up front): the 3D shape slots that the       */
/* initialized tables below point into.  dseg 0x42DBC: 130 * 22 bytes, */
/* all zero (filled at runtime by shape3d_load_all).                   */
/* ------------------------------------------------------------------ */
struct SHAPE3D game3dshapes[130];
char far* curshapeptr;   /* dseg 0x449FA: dd 0 */
char far* game1ptr;      /* dseg 0x46052: dd 0 */
char far* game2ptr;      /* dseg 0x46352: dd 0 */

/* ------------------------------------------------------------------ */
/* Group 1: pure data tables                                           */
/* ------------------------------------------------------------------ */

/* dseg 0x3C1C0 (aBarn..aExp3): 3D shape resource name list, 0x74 = 116
 * names at a 5-byte stride; byte-identical to sdl/data3d.cpp. */
char aBarn[] =
	"barn\0" "zbrn\0" "brid\0" "zbri\0" "btur\0" "zbtu\0" "chi1\0" "zch1\0"
	"chi2\0" "zch2\0" "elrd\0" "zelr\0" "fini\0" "zfin\0" "gass\0" "zgas\0"
	"lban\0" "zlba\0" "loop\0" "zloo\0" "offi\0" "zoff\0" "pipe\0" "zpip\0"
	"ramp\0" "zram\0" "rban\0" "zrba\0" "rdup\0" "zrdu\0" "road\0" "zroa\0"
	"stur\0" "zstu\0" "tenn\0" "zten\0" "tunn\0" "ztun\0" "turn\0" "ztur\0"
	"goui\0" "gouo\0" "goup\0" "high\0" "lakc\0" "lake\0" "cld1\0" "cld2\0"
	"cld3\0" "sigl\0" "sigr\0" "tree\0" "inte\0" "zint\0" "offl\0" "zofl\0"
	"offr\0" "zofr\0" "palm\0" "zpal\0" "bank\0" "zban\0" "sofl\0" "zsol\0"
	"sofr\0" "zsor\0" "sram\0" "zsra\0" "selr\0" "zser\0" "elsp\0" "zesp\0"
	"cact\0" "cact\0" "spip\0" "zspi\0" "sest\0" "zses\0" "wroa\0" "zwro\0"
	"barr\0" "zbar\0" "lco0\0" "zlco\0" "rco0\0" "zrco\0" "gwro\0" "zgwr\0"
	"lco1\0" "rco1\0" "loo1\0" "hig1\0" "hig2\0" "hig3\0" "wind\0" "zwin\0"
	"boat\0" "zboa\0" "rest\0" "zres\0" "hpip\0" "zhpi\0" "vcor\0" "zvco\0"
	"tun2\0" "pip2\0" "fenc\0" "zfen\0" "cfen\0" "zcfe\0" "flag\0" "truk\0"
	"exp0\0" "exp1\0" "exp2\0" "exp3";
_Static_assert(sizeof(aBarn) == 0x74 * 5, "aBarn is 116 5-byte names");

/* dseg 0x3F871: atan lookup, 258 bytes (matches sdl/main.cpp). */
uint8_t atantable[258] = {
	0, 1, 1, 2, 3, 3, 4, 4, 5, 6, 6, 7, 8, 8, 9, 10,
	10, 11, 11, 12, 13, 13, 14, 15, 15, 16, 16, 17, 18, 18, 19, 20,
	20, 21, 22, 22, 23, 23, 24, 25, 25, 26, 27, 27, 28, 28, 29, 30,
	30, 31, 31, 32, 33, 33, 34, 34, 35, 36, 36, 37, 38, 38, 39, 39,
	40, 41, 41, 42, 42, 43, 44, 44, 45, 45, 46, 46, 47, 48, 48, 49,
	49, 50, 51, 51, 52, 52, 53, 53, 54, 55, 55, 56, 56, 57, 57, 58,
	58, 59, 60, 60, 61, 61, 62, 62, 63, 63, 64, 65, 65, 66, 66, 67,
	67, 68, 68, 69, 69, 70, 70, 71, 71, 72, 72, 73, 74, 74, 75, 75,
	76, 76, 77, 77, 78, 78, 79, 79, 80, 80, 81, 81, 82, 82, 83, 83,
	84, 84, 84, 85, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 90, 91,
	91, 91, 92, 92, 93, 93, 94, 94, 95, 95, 96, 96, 96, 97, 97, 98,
	98, 99, 99, 99, 100, 100, 101, 101, 102, 102, 102, 103, 103, 104, 104, 104,
	105, 105, 106, 106, 106, 107, 107, 108, 108, 108, 109, 109, 110, 110, 110, 111,
	111, 112, 112, 112, 113, 113, 113, 114, 114, 115, 115, 115, 116, 116, 116, 117,
	117, 118, 118, 118, 119, 119, 119, 120, 120, 120, 121, 121, 121, 122, 122, 122,
	123, 123, 123, 124, 124, 124, 125, 125, 125, 126, 126, 126, 127, 127, 127, 128,
	128, 0,
};

/* dseg 0x3EFC6: primitive type codes (matches sdl/main.cpp). */
uint8_t primtypetab[16] = {
	0, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 0, 0,
};

/* dseg 0x3EFB6: primitive index counts (matches sdl/main.cpp). */
uint8_t primidxcounttab[16] = {
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 6, 3, 0, 0,
};

/* dseg 0x3EFD6: 1/2^n table, 32 dd entries.  NOTE: sdl/main.cpp has a typo
 * at index 4 (decimal 8000000 instead of 0x8000000); dseg.asm is authoritative
 * and holds the exact power of two, 134217728. */
int32_t invpow2tbl[32] = {
	INT32_MIN /* 0x80000000 */, 1073741824, 536870912, 268435456,
	134217728, 67108864, 33554432, 16777216,
	8388608, 4194304, 2097152, 1048576,
	524288, 262144, 131072, 65536,
	32768, 16384, 8192, 4096,
	2048, 1024, 512, 256,
	128, 64, 32, 16,
	8, 4, 2, 1,
};

/* dseg 0x44DD2 / 0x44ED4 / 0x44FD6: material tables, 129 dw each
 * (bit-identical to sdl/main.cpp, which prints them as unsigned hex). */
int16_t material_color_list[129] = {
	0, 1, 2, 3, 4, 5, 6, 7,
	8, 9, 10, 11, 12, 13, 14, 15,
	108, 116, 15, 28, 29, 14, 28, 31,
	14, 200, 198, 196, 112, 114, 116, 194,
	197, 200, 146, 37, 35, 181, 29, 31,
	19, 3, 11, 27, 0, 4, 4, 12,
	156, 154, 152, 150, 42, 40, 38, 37,
	27, 26, 25, 24, 72, 70, 68, 66,
	123, 121, 120, 117, 92, 90, 88, 87,
	173, 171, 169, 167, 20, 19, 18, 17,
	77, 76, 74, 73, 45, 44, 42, 41,
	159, 175, 174, 172, 29, 28, 18, 90,
	15, 7, 200, 219, 136, 99, 101, 103,
	104, 106, 17, 20, 60, 77, 46, 61,
	45, 202, 190, 186, 183, 180, 0, 28,
	30, 16, 20, 68, 54, 39, 43, 12,
	17,
};

int16_t material_pattern_list[129] = {
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
	0,
};

int16_t material_pattern2_list[129] = {
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, 0, -1, -1, -1, 0x77DD, /*0xDD77*/ -8841,
	0x77DD, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, 0x77DD, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0x77DD, -1,
	-1, -1, -1, -1, -1, -1, -1, -1,
	-1, -1, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, /*0xCC33*/ -13261,
	0x33CC, /*0xB66D*/ -18835, 0x4992, -18835, 0x4992, -18835, 0x4992, 0,
	0,
};

/* dseg 0x3BE54..0x3C083: eight 70-byte lookahead tile tables.  Each record is
 * (dcol, drow, weight) tile offsets; table choice depends on car heading.
 * Values are exact dseg.asm bytes (signed). */
char unk_3BE54[70] = {
	-2, -4, 2, -1, -4, 2, 0, -4, 2, 1, -4, 2, 2, -4,
	2, -2, -3, 1, -1, -3, 1, 0, -3, 1, 1, -3, 1, 2,
	-3, 1, -2, -2, 1, -1, -2, 0, 0, -2, 0, 1, -2, 0,
	2, -2, 1, -2, -1, 0, -1, -1, 0, 0, -1, 0, 1, -1,
	0, 2, -1, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
};
char unk_3BE9A[70] = {
	2, -4, 2, 1, -4, 2, 0, -4, 2, -1, -4, 2, -2, -4,
	2, 2, -3, 1, 1, -3, 1, 0, -3, 1, -1, -3, 1, -2,
	-3, 1, 2, -2, 1, 1, -2, 0, 0, -2, 0, -1, -2, 0,
	-2, -2, 1, 2, -1, 0, 1, -1, 0, 0, -1, 0, -1, -1,
	0, -2, -1, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0,
};
char unk_3BEE0[70] = {
	4, -2, 2, 4, -1, 2, 4, 0, 2, 4, 1, 2, 4, 2,
	2, 3, -2, 1, 3, -1, 1, 3, 0, 1, 3, 1, 1, 3,
	2, 1, 2, -2, 1, 2, -1, 0, 2, 0, 0, 2, 1, 0,
	2, 2, 1, 1, -2, 0, 1, -1, 0, 1, 0, 0, 1, 1,
	0, 2, 2, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0,
};
char unk_3BF26[70] = {
	4, 2, 2, 4, 1, 2, 4, 0, 2, 4, -1, 2, 4, -2,
	2, 3, 2, 1, 3, 1, 1, 3, 0, 1, 3, -1, 1, 3,
	-2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 0, 2, -1, 0,
	2, -2, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1, -1,
	0, 1, -2, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0,
};
char unk_3BF6C[70] = {
	2, 4, 2, 1, 4, 2, 0, 4, 2, -1, 4, 2, -2, 4,
	2, 2, 3, 1, 1, 3, 1, 0, 3, 1, -1, 3, 1, -2,
	3, 1, 2, 2, 0, 1, 2, 0, 0, 2, 0, -1, 2, 0,
	-2, 2, 1, 2, 1, 0, 1, 1, 0, 0, 1, 0, -1, 1,
	0, -2, 1, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0, 0,
};
char unk_3BFB2[70] = {
	-2, 4, 2, -1, 4, 2, 0, 4, 2, 1, 4, 2, 2, 4,
	2, -2, 3, 1, -1, 3, 1, 0, 3, 1, 1, 3, 1, 2,
	3, 1, -2, 2, 1, -1, 2, 0, 0, 2, 0, 1, 2, 0,
	2, 2, 1, -2, 1, 0, -1, 1, 0, 0, 1, 0, 1, 1,
	0, 2, 1, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
};
char unk_3BFF8[70] = {
	-4, 2, 2, -4, 1, 2, -4, 0, 2, -4, -1, 2, -4, -2,
	2, -3, 2, 1, -3, 1, 1, -3, 0, 1, -3, -1, 1, -3,
	-2, 1, -2, 2, 1, -2, 1, 0, -2, 0, 0, -2, -1, 0,
	-2, -2, 1, -1, 2, 0, -1, 1, 0, -1, 0, 0, -1, -1,
	0, -1, -2, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0, 0,
};
char unk_3C03E[70] = {
	-4, -2, 2, -4, -1, 2, -4, 0, 2, -4, 1, 2, -4, 2,
	2, -3, -2, 1, -3, -1, 1, -3, 0, 1, -3, 1, 1, -3,
	2, 1, -2, -2, 1, -2, -1, 0, -2, 0, 0, -2, 1, 0,
	-2, 2, 1, -1, -2, 0, -1, -1, 0, -1, 0, 0, -1, 1,
	0, -1, 2, 0, 0, -1, 0, 0, 1, 0, 0, 0, 0, 0,
};

/* dseg 0x3C084: dw offset table, same order as dseg.asm. */
char* lookahead_tiles_tables[8] = {
	unk_3BE9A, unk_3BEE0, unk_3BF26, unk_3BF6C,
	unk_3BFB2, unk_3BFF8, unk_3C03E, unk_3BE54,
};

/* dseg 0x3C094 */
char detail_threshold_by_level[6] = { 2, 2, 1, 0, 0, 0 };

/* dseg 0x3C0C6 */
char byte_3C0C6[16] = { 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3 };

/* dseg 0x3C0E6: trkObjectList codes for the four track-boundary fences. */
uint8_t fence_TrkObjCodes[8] = { 214, 215, 214, 215, 214, 215, 214, 215 };

/* dseg 0x3C0A2 / 0x3C0A6 / 0x3C0AE / 0x3C0B6 (db pairs, little-endian dw). */
int16_t unk_3C0A2[2] = { 0, 0 };
int16_t unk_3C0A6[4] = { 0, 512, 0, -512 };
int16_t unk_3C0AE[4] = { 512, 0, -512, 0 };
int16_t unk_3C0B6[8] = { -512, 512, -512, -512, 512, 512, 512, -512 };

/* dseg 0x3C0EE / 0x3C0F0 / 0x3C0F4 / 0x3C0F8 */
char unk_3C0EE[2] = { 0, 0 };
char unk_3C0F0[4] = { 0, 0, 0, 1 };
char unk_3C0F4[4] = { 0, 0, 1, 0 };
char unk_3C0F8[16] = { 0, 0, 1, 0, 0, 1, 1, 1, 128, 0, 128, 1, 128, 2, 128, 3 };

/* dseg 0x3C0D6 (dw + db pairs, little-endian) */
int16_t word_3C0D6[8] = { 0, 0, 256, 256, 512, 512, 768, 768 };

/* dseg 0x3BE34: distance thresholds. */
int16_t word_3BE34[8] = { 30, 200, 320, 400, 530, 700, 880, 960 };

/* dseg 0x449FC: dw 0; the dw at 0x449FE (dseg word_449FE) is element [1] --
 * frame.c indexes word_449FC[arg] for player/opponent. */
int16_t word_449FC[2] = { 0, 0 };

/* dseg 0x3B8EC */
int16_t hillHeightConsts[2] = { 0, 450 };

/* dseg 0x46468: dw 0 in dseg; declared 'extern char' by frame.c (authority). */
char word_46468 = 0;

/* dseg 0x3BE16 */
int16_t word_3BE16 = 9999;

/* dseg trackdata pointer slots (all dd 0 = NULL far pointers, set at load). */
int16_t far* trackdata9;         /* dseg 0x449EC */
uint8_t far* trackdata19;        /* dseg 0x45E5A */
uint8_t far* trackdata23;        /* dseg 0x46356 */
int16_t far* td08_direction_related; /* dseg 0x45C36 */
int16_t far* td10_track_check_rel;   /* dseg 0x4402C */

/* dseg 0x3E710 */
char unk_3E710[8];

int16_t word_44DCA;  /* dseg 0x44DCA: dw 0 */
int16_t word_44D20;  /* dseg 0x44D20: dw 0 */
int16_t roofbmpheight; /* dseg 0x460BE: dw 0 */
int16_t dashbmp_y;     /* dseg 0x460C0: dw 0 - first screen row of the dash */
char dashb_toggle = 1; /* dseg: show the cockpit panel (the original F-key) */

/* dseg 0x442F* projection state (declared uint16_t in shape3d.c). */
uint16_t projectiondata1 = 0;
uint16_t projectiondata2 = 0;
uint16_t projectiondata3 = 160;
uint16_t projectiondata4 = 0;
uint16_t projectiondata5 = 160;
uint16_t projectiondata6 = 100;
uint16_t projectiondata7 = 0;
uint16_t projectiondata8 = 100;
uint16_t projectiondata9 = 0;
uint16_t projectiondata10 = 0;

/* dseg 0x45912: dw 0 + 2 db pairs, all zero. */
int16_t sdgame2_widths[3];

/* ------------------------------------------------------------------ */
/* Group 2 + coordinator correction: initialized shape/track tables    */
/* generated by tools/extract_dseg_tables.py                           */
/* ------------------------------------------------------------------ */
/* Generated by tools/extract_dseg_tables.py -- do not hand-edit the
   tables below; regenerate instead. */

/* dseg 0x3BE44: dw offset game3dshapes+NNNh -> &game3dshapes[NNN/22] (DOS sizeof(SHAPE3D) == 22) */
struct SHAPE3D* off_3BE44[8] = {
	&game3dshapes[48], /* +0x420 = 1056 = 48*22 */
	&game3dshapes[47], /* +0x40A = 1034 = 47*22 */
	&game3dshapes[46], /* +0x3F4 = 1012 = 46*22 */
	&game3dshapes[48], /* +0x420 = 1056 = 48*22 */
	&game3dshapes[47], /* +0x40A = 1034 = 47*22 */
	&game3dshapes[46], /* +0x3F4 = 1012 = 46*22 */
	&game3dshapes[48], /* +0x420 = 1056 = 48*22 */
	&game3dshapes[47], /* +0x40A = 1034 = 47*22 */
};

/* dseg 0x3D808: 215 entries x 14 DOS bytes, transcribed from dseg.asm.
   ss_shapePtr/ss_loShapePtr are patched to &game3dshapes[i] at startup
   from trkObjectList_shapeidx[] (misaligned-pointer-relocation workaround -- see tools/extract_dseg_tables.py). */
struct TRACKOBJECT trkObjectList[215] = {
	{ 0, 0, 0, 0, 0, 0, 0, 0, 64, 0 }, /* [0] shapes 30/30; */
	{ (struct TRKOBJINFO*)0x1A24, 0, 0, 0, 4, 0, 0, 0, 0, 0 }, /* [1] shapes 12/13; dseg:shapeinfos[2]; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 64, 0 }, /* [2] shapes 126/128; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 64, 0 }, /* [3] shapes 127/129; */
	{ (struct TRKOBJINFO*)0x1A5C, 0, 0, 0, 0, 0, 1, 0, 1, 0 }, /* [4] shapes 30/31; dseg:shapeinfos[6]; */
	{ (struct TRKOBJINFO*)0x1A6A, 256, 0, 0, 0, 0, 1, 0, 1, 0 }, /* [5] shapes 30/31; dseg:shapeinfos[7]; */
	{ (struct TRKOBJINFO*)0x1AB0, 768, 0, 0, 0, 0, 1, 0, 2, 0 }, /* [6] shapes 38/39; dseg:shapeinfos[12]; */
	{ (struct TRKOBJINFO*)0x1ABE, 0, 0, 0, 0, 0, 1, 0, 2, 0 }, /* [7] shapes 38/39; dseg:shapeinfos[13]; */
	{ (struct TRKOBJINFO*)0x1ACC, 512, 0, 0, 0, 0, 1, 0, 2, 0 }, /* [8] shapes 38/39; dseg:shapeinfos[14]; */
	{ (struct TRKOBJINFO*)0x1ADA, 256, 0, 0, 0, 0, 1, 0, 2, 0 }, /* [9] shapes 38/39; dseg:shapeinfos[15]; */
	{ (struct TRKOBJINFO*)0x1AE8, 768, 0, 0, 0, 0, 1, 3, 3, 0 }, /* [10] shapes 32/33; dseg:shapeinfos[16]; */
	{ (struct TRKOBJINFO*)0x1AF6, 0, 0, 0, 0, 0, 1, 3, 3, 0 }, /* [11] shapes 32/33; dseg:shapeinfos[17]; */
	{ (struct TRKOBJINFO*)0x1B04, 512, 0, 0, 0, 0, 1, 3, 3, 0 }, /* [12] shapes 32/33; dseg:shapeinfos[18]; */
	{ (struct TRKOBJINFO*)0x1B12, 256, 0, 0, 0, 0, 1, 3, 3, 0 }, /* [13] shapes 32/33; dseg:shapeinfos[19]; */
	{ (struct TRKOBJINFO*)0x1A5C, 0, 0, 0, 0, 1, 1, 0, 1, 0 }, /* [14] shapes 30/31; dseg:shapeinfos[6]; */
	{ (struct TRKOBJINFO*)0x1A6A, 256, 0, 0, 0, 1, 1, 0, 1, 0 }, /* [15] shapes 30/31; dseg:shapeinfos[7]; */
	{ (struct TRKOBJINFO*)0x1AB0, 768, 0, 0, 0, 1, 1, 0, 2, 0 }, /* [16] shapes 38/39; dseg:shapeinfos[12]; */
	{ (struct TRKOBJINFO*)0x1ABE, 0, 0, 0, 0, 1, 1, 0, 2, 0 }, /* [17] shapes 38/39; dseg:shapeinfos[13]; */
	{ (struct TRKOBJINFO*)0x1ACC, 512, 0, 0, 0, 1, 1, 0, 2, 0 }, /* [18] shapes 38/39; dseg:shapeinfos[14]; */
	{ (struct TRKOBJINFO*)0x1ADA, 256, 0, 0, 0, 1, 1, 0, 2, 0 }, /* [19] shapes 38/39; dseg:shapeinfos[15]; */
	{ (struct TRKOBJINFO*)0x1AE8, 768, 0, 0, 0, 1, 1, 3, 3, 0 }, /* [20] shapes 32/33; dseg:shapeinfos[16]; */
	{ (struct TRKOBJINFO*)0x1AF6, 0, 0, 0, 0, 1, 1, 3, 3, 0 }, /* [21] shapes 32/33; dseg:shapeinfos[17]; */
	{ (struct TRKOBJINFO*)0x1B04, 512, 0, 0, 0, 1, 1, 3, 3, 0 }, /* [22] shapes 32/33; dseg:shapeinfos[18]; */
	{ (struct TRKOBJINFO*)0x1B12, 256, 0, 0, 0, 1, 1, 3, 3, 0 }, /* [23] shapes 32/33; dseg:shapeinfos[19]; */
	{ (struct TRKOBJINFO*)0x1A5C, 0, 0, 0, 0, 2, 1, 0, 1, 0 }, /* [24] shapes 30/31; dseg:shapeinfos[6]; */
	{ (struct TRKOBJINFO*)0x1A6A, 256, 0, 0, 0, 2, 1, 0, 1, 0 }, /* [25] shapes 30/31; dseg:shapeinfos[7]; */
	{ (struct TRKOBJINFO*)0x1AB0, 768, 0, 0, 0, 2, 1, 0, 2, 0 }, /* [26] shapes 38/39; dseg:shapeinfos[12]; */
	{ (struct TRKOBJINFO*)0x1ABE, 0, 0, 0, 0, 2, 1, 0, 2, 0 }, /* [27] shapes 38/39; dseg:shapeinfos[13]; */
	{ (struct TRKOBJINFO*)0x1ACC, 512, 0, 0, 0, 2, 1, 0, 2, 0 }, /* [28] shapes 38/39; dseg:shapeinfos[14]; */
	{ (struct TRKOBJINFO*)0x1ADA, 256, 0, 0, 0, 2, 1, 0, 2, 0 }, /* [29] shapes 38/39; dseg:shapeinfos[15]; */
	{ (struct TRKOBJINFO*)0x1AE8, 768, 0, 0, 0, 2, 1, 3, 3, 0 }, /* [30] shapes 32/33; dseg:shapeinfos[16]; */
	{ (struct TRKOBJINFO*)0x1AF6, 0, 0, 0, 0, 2, 1, 3, 3, 0 }, /* [31] shapes 32/33; dseg:shapeinfos[17]; */
	{ (struct TRKOBJINFO*)0x1B04, 512, 0, 0, 0, 2, 1, 3, 3, 0 }, /* [32] shapes 32/33; dseg:shapeinfos[18]; */
	{ (struct TRKOBJINFO*)0x1B12, 256, 0, 0, 0, 2, 1, 3, 3, 0 }, /* [33] shapes 32/33; dseg:shapeinfos[19]; */
	{ (struct TRKOBJINFO*)0x1B20, 0, 0, 0, 0, 0, 0, 0, 18, 0 }, /* [34] shapes 10/11; dseg:shapeinfos[20]; */
	{ (struct TRKOBJINFO*)0x1B2E, 768, 0, 0, 0, 0, 0, 0, 18, 0 }, /* [35] shapes 10/11; dseg:shapeinfos[21]; */
	{ (struct TRKOBJINFO*)0x1C0E, 256, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [36] shapes 24/25; dseg:shapeinfos[37]; */
	{ (struct TRKOBJINFO*)0x1C00, 768, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [37] shapes 24/25; dseg:shapeinfos[36]; */
	{ (struct TRKOBJINFO*)0x1BF2, 0, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [38] shapes 24/25; dseg:shapeinfos[35]; */
	{ (struct TRKOBJINFO*)0x1BE4, 512, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [39] shapes 24/25; dseg:shapeinfos[34]; */
	{ (struct TRKOBJINFO*)0x1C70, 0, 0, 0, 0, 0, 0, 0, 24, 0 }, /* [40] shapes 26/27; dseg:shapeinfos[44]; */
	{ (struct TRKOBJINFO*)0x1C7E, 256, 0, 0, 0, 0, 0, 0, 24, 0 }, /* [41] shapes 26/27; dseg:shapeinfos[45]; */
	{ (struct TRKOBJINFO*)0x1C54, 512, 0, 0, 0, 0, 0, 0, 24, 0 }, /* [42] shapes 26/27; dseg:shapeinfos[42]; */
	{ (struct TRKOBJINFO*)0x1C62, 768, 0, 0, 0, 0, 0, 0, 24, 0 }, /* [43] shapes 26/27; dseg:shapeinfos[43]; */
	{ (struct TRKOBJINFO*)0x1CA8, 0, 0, 0, 0, 0, 0, 0, 23, 0 }, /* [44] shapes 16/17; dseg:shapeinfos[48]; */
	{ (struct TRKOBJINFO*)0x1CB6, 256, 0, 0, 0, 0, 0, 0, 23, 0 }, /* [45] shapes 16/17; dseg:shapeinfos[49]; */
	{ (struct TRKOBJINFO*)0x1C8C, 512, 0, 0, 0, 0, 0, 0, 23, 0 }, /* [46] shapes 16/17; dseg:shapeinfos[46]; */
	{ (struct TRKOBJINFO*)0x1C9A, 768, 0, 0, 0, 0, 0, 0, 23, 0 }, /* [47] shapes 16/17; dseg:shapeinfos[47]; */
	{ (struct TRKOBJINFO*)0x1CE0, 512, 0, 0, 0, 0, 0, 0, 25, 0 }, /* [48] shapes 60/61; dseg:shapeinfos[52]; */
	{ (struct TRKOBJINFO*)0x1CC4, 0, 0, 0, 0, 0, 0, 0, 25, 0 }, /* [49] shapes 60/61; dseg:shapeinfos[50]; */
	{ (struct TRKOBJINFO*)0x1CEE, 768, 0, 0, 0, 0, 0, 0, 25, 0 }, /* [50] shapes 60/61; dseg:shapeinfos[53]; */
	{ (struct TRKOBJINFO*)0x1CD2, 256, 0, 0, 0, 0, 0, 0, 25, 0 }, /* [51] shapes 60/61; dseg:shapeinfos[51]; */
	{ (struct TRKOBJINFO*)0x1CFC, 768, 0, 0, 0, 0, 0, 3, 26, 0 }, /* [52] shapes 4/5; dseg:shapeinfos[54]; */
	{ (struct TRKOBJINFO*)0x1D0A, 0, 0, 0, 0, 0, 0, 3, 26, 0 }, /* [53] shapes 4/5; dseg:shapeinfos[55]; */
	{ (struct TRKOBJINFO*)0x1D18, 512, 0, 0, 0, 0, 0, 3, 26, 0 }, /* [54] shapes 4/5; dseg:shapeinfos[56]; */
	{ (struct TRKOBJINFO*)0x1D26, 256, 0, 0, 0, 0, 0, 3, 26, 0 }, /* [55] shapes 4/5; dseg:shapeinfos[57]; */
	{ (struct TRKOBJINFO*)0x1C0E, 256, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [56] shapes 2/3; dseg:shapeinfos[37]; */
	{ (struct TRKOBJINFO*)0x1C00, 768, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [57] shapes 2/3; dseg:shapeinfos[36]; */
	{ (struct TRKOBJINFO*)0x1BF2, 0, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [58] shapes 2/3; dseg:shapeinfos[35]; */
	{ (struct TRKOBJINFO*)0x1BE4, 512, 0, 0, 0, 0, 0, 0, 16, 0 }, /* [59] shapes 2/3; dseg:shapeinfos[34]; */
	{ (struct TRKOBJINFO*)0x1DC0, 0, 0, 0, 0, 0, 1, 3, 5, 0 }, /* [60] shapes 8/9; dseg:shapeinfos[68]; */
	{ (struct TRKOBJINFO*)0x1DCE, 256, 0, 0, 0, 0, 1, 3, 4, 0 }, /* [61] shapes 6/7; dseg:shapeinfos[69]; */
	{ (struct TRKOBJINFO*)0x1DDC, 0, 0, 0, 0, 0, 1, 3, 4, 0 }, /* [62] shapes 6/7; dseg:shapeinfos[70]; */
	{ (struct TRKOBJINFO*)0x1DEA, 256, 0, 0, 0, 0, 1, 3, 5, 0 }, /* [63] shapes 8/9; dseg:shapeinfos[71]; */
	{ (struct TRKOBJINFO*)0x1D34, 0, 0, 0, 0xCE, 0, 0, 1, 27, 0 }, /* [64] shapes 18/19; dseg:shapeinfos[58]; */
	{ (struct TRKOBJINFO*)0x1D42, 256, 0, 0, 0xCF, 0, 0, 2, 27, 0 }, /* [65] shapes 18/19; dseg:shapeinfos[59]; */
	{ (struct TRKOBJINFO*)0x1A78, 0, 0, 0, 0xD0, 0, 0, 0, 28, 0 }, /* [66] shapes 36/37; dseg:shapeinfos[8]; */
	{ (struct TRKOBJINFO*)0x1A86, 768, 0, 0, 0xD1, 0, 0, 0, 28, 0 }, /* [67] shapes 36/37; dseg:shapeinfos[9]; */
	{ (struct TRKOBJINFO*)0x1D50, 0, 0, 0, 0xD2, 0, 0, 0, 30, 0 }, /* [68] shapes 22/23; dseg:shapeinfos[60]; */
	{ (struct TRKOBJINFO*)0x1D5E, 256, 0, 0, 0xD3, 0, 0, 0, 30, 0 }, /* [69] shapes 22/23; dseg:shapeinfos[61]; */
	{ (struct TRKOBJINFO*)0x1D96, 0, 0, 0, 0, 0, 0, 0, 29, 0 }, /* [70] shapes 74/75; dseg:shapeinfos[65]; */
	{ (struct TRKOBJINFO*)0x1D88, 512, 0, 0, 0, 0, 0, 0, 29, 0 }, /* [71] shapes 74/75; dseg:shapeinfos[64]; */
	{ (struct TRKOBJINFO*)0x1DA4, 768, 0, 0, 0, 0, 0, 0, 29, 0 }, /* [72] shapes 74/75; dseg:shapeinfos[66]; */
	{ (struct TRKOBJINFO*)0x1DB2, 256, 0, 0, 0, 0, 0, 0, 29, 0 }, /* [73] shapes 74/75; dseg:shapeinfos[67]; */
	{ (struct TRKOBJINFO*)0x1A94, 0, 0, 0, 0, 0, 0, 0, 12, 0 }, /* [74] shapes 52/53; dseg:shapeinfos[10]; */
	{ (struct TRKOBJINFO*)0x1DF8, 0, 0, 0, 0, 0, 0, 0, 6, 0 }, /* [75] shapes 54/55; dseg:shapeinfos[72]; */
	{ (struct TRKOBJINFO*)0x1E14, 768, 0, 0, 0, 0, 0, 0, 6, 0 }, /* [76] shapes 54/55; dseg:shapeinfos[74]; */
	{ (struct TRKOBJINFO*)0x1E30, 512, 0, 0, 0, 0, 0, 0, 6, 0 }, /* [77] shapes 54/55; dseg:shapeinfos[76]; */
	{ (struct TRKOBJINFO*)0x1E4C, 256, 0, 0, 0, 0, 0, 0, 6, 0 }, /* [78] shapes 54/55; dseg:shapeinfos[78]; */
	{ (struct TRKOBJINFO*)0x1E68, 0, 0, 0, 0, 0, 0, 0, 7, 0 }, /* [79] shapes 56/57; dseg:shapeinfos[80]; */
	{ (struct TRKOBJINFO*)0x1E84, 768, 0, 0, 0, 0, 0, 0, 7, 0 }, /* [80] shapes 56/57; dseg:shapeinfos[82]; */
	{ (struct TRKOBJINFO*)0x1EA0, 512, 0, 0, 0, 0, 0, 0, 7, 0 }, /* [81] shapes 56/57; dseg:shapeinfos[84]; */
	{ (struct TRKOBJINFO*)0x1EBC, 256, 0, 0, 0, 0, 0, 0, 7, 0 }, /* [82] shapes 56/57; dseg:shapeinfos[86]; */
	{ (struct TRKOBJINFO*)0x1D6C, 0, 0, 0, 0xD2, 0, 0, 0, 31, 0 }, /* [83] shapes 100/101; dseg:shapeinfos[62]; */
	{ (struct TRKOBJINFO*)0x1D7A, 256, 0, 0, 0xD3, 0, 0, 0, 31, 0 }, /* [84] shapes 100/101; dseg:shapeinfos[63]; */
	{ (struct TRKOBJINFO*)0x1A08, 0, 0, 0, 0, 0, 0, 1, 35, 0 }, /* [85] shapes 102/103; dseg:shapeinfos[0]; */
	{ (struct TRKOBJINFO*)0x1A16, 256, 0, 0, 0, 0, 0, 2, 35, 0 }, /* [86] shapes 102/103; dseg:shapeinfos[1]; */
	{ (struct TRKOBJINFO*)0x1ED8, 0, 0, 0, 0, 0, 1, 3, 8, 0 }, /* [87] shapes 62/63; dseg:shapeinfos[88]; */
	{ (struct TRKOBJINFO*)0x1EF4, 768, 0, 0, 0, 0, 1, 3, 8, 0 }, /* [88] shapes 62/63; dseg:shapeinfos[90]; */
	{ (struct TRKOBJINFO*)0x1F10, 512, 0, 0, 0, 0, 1, 3, 8, 0 }, /* [89] shapes 62/63; dseg:shapeinfos[92]; */
	{ (struct TRKOBJINFO*)0x1F2C, 256, 0, 0, 0, 0, 1, 3, 8, 0 }, /* [90] shapes 62/63; dseg:shapeinfos[94]; */
	{ (struct TRKOBJINFO*)0x1F48, 0, 0, 0, 0, 0, 1, 3, 9, 0 }, /* [91] shapes 64/65; dseg:shapeinfos[96]; */
	{ (struct TRKOBJINFO*)0x1F64, 768, 0, 0, 0, 0, 1, 3, 9, 0 }, /* [92] shapes 64/65; dseg:shapeinfos[98]; */
	{ (struct TRKOBJINFO*)0x1F80, 512, 0, 0, 0, 0, 1, 3, 9, 0 }, /* [93] shapes 64/65; dseg:shapeinfos[100]; */
	{ (struct TRKOBJINFO*)0x1F9C, 256, 0, 0, 0, 0, 1, 3, 9, 0 }, /* [94] shapes 64/65; dseg:shapeinfos[102]; */
	{ (struct TRKOBJINFO*)0x1C0E, 256, 0, 0, 0, 0, 0, 0, 17, 0 }, /* [95] shapes 66/67; dseg:shapeinfos[37]; */
	{ (struct TRKOBJINFO*)0x1C00, 768, 0, 0, 0, 0, 0, 0, 17, 0 }, /* [96] shapes 66/67; dseg:shapeinfos[36]; */
	{ (struct TRKOBJINFO*)0x1BF2, 0, 0, 0, 0, 0, 0, 0, 17, 0 }, /* [97] shapes 66/67; dseg:shapeinfos[35]; */
	{ (struct TRKOBJINFO*)0x1BE4, 512, 0, 0, 0, 0, 0, 0, 17, 0 }, /* [98] shapes 66/67; dseg:shapeinfos[34]; */
	{ (struct TRKOBJINFO*)0x1B20, 0, 0, 0, 0, 0, 0, 0, 20, 0 }, /* [99] shapes 68/69; dseg:shapeinfos[20]; */
	{ (struct TRKOBJINFO*)0x1B2E, 768, 0, 0, 0, 0, 0, 0, 20, 0 }, /* [100] shapes 68/69; dseg:shapeinfos[21]; */
	{ (struct TRKOBJINFO*)0x1B3C, 0, 0, 0, 5, 0, 0, 0, 22, 0 }, /* [101] shapes 70/71; dseg:shapeinfos[22]; */
	{ (struct TRKOBJINFO*)0x1B58, 768, 0, 0, 4, 0, 0, 0, 22, 0 }, /* [102] shapes 70/71; dseg:shapeinfos[24]; */
	{ (struct TRKOBJINFO*)0x1B20, 0, 0, 0, 0, 0, 0, 0, 19, 0 }, /* [103] shapes 70/71; dseg:shapeinfos[20]; */
	{ (struct TRKOBJINFO*)0x1B2E, 768, 0, 0, 0, 0, 0, 0, 19, 0 }, /* [104] shapes 70/71; dseg:shapeinfos[21]; */
	{ (struct TRKOBJINFO*)0x1B74, 768, 0, 0, 0, 0, 0, 3, 21, 0 }, /* [105] shapes 76/77; dseg:shapeinfos[26]; */
	{ (struct TRKOBJINFO*)0x1B82, 0, 0, 0, 0, 0, 0, 3, 21, 0 }, /* [106] shapes 76/77; dseg:shapeinfos[27]; */
	{ (struct TRKOBJINFO*)0x1B90, 512, 0, 0, 0, 0, 0, 3, 21, 0 }, /* [107] shapes 76/77; dseg:shapeinfos[28]; */
	{ (struct TRKOBJINFO*)0x1B9E, 256, 0, 0, 0, 0, 0, 3, 21, 0 }, /* [108] shapes 76/77; dseg:shapeinfos[29]; */
	{ (struct TRKOBJINFO*)0x1FB8, 0, 0, 0, 0, 0, 0, 0, 11, 0 }, /* [109] shapes 78/79; dseg:shapeinfos[104]; */
	{ (struct TRKOBJINFO*)0x1FC6, 768, 0, 0, 0, 0, 0, 0, 11, 0 }, /* [110] shapes 78/79; dseg:shapeinfos[105]; */
	{ (struct TRKOBJINFO*)0x1FE2, 0, 0, 0, 0, 0xFF, 0, 0, 10, 0 }, /* [111] shapes 86/87; dseg:shapeinfos[107]; */
	{ (struct TRKOBJINFO*)0x1FFE, 256, 0, 0, 0, 0xFF, 0, 0, 10, 0 }, /* [112] shapes 86/87; dseg:shapeinfos[109]; */
	{ (struct TRKOBJINFO*)0x1FD4, 512, 0, 0, 0, 0xFF, 0, 0, 10, 0 }, /* [113] shapes 86/87; dseg:shapeinfos[106]; */
	{ (struct TRKOBJINFO*)0x1FF0, 768, 0, 0, 0, 0xFF, 0, 0, 10, 0 }, /* [114] shapes 86/87; dseg:shapeinfos[108]; */
	{ (struct TRKOBJINFO*)0x200C, 0, 0, 0, 4, 0, 0, 0, 34, 0 }, /* [115] shapes 80/81; dseg:shapeinfos[110]; */
	{ (struct TRKOBJINFO*)0x201A, 768, 0, 0, 5, 0, 0, 0, 34, 0 }, /* [116] shapes 80/81; dseg:shapeinfos[111]; */
	{ (struct TRKOBJINFO*)0x2028, 0, 0, 0, 0xC6, 0, 0, 3, 32, 0 }, /* [117] shapes 82/83; dseg:shapeinfos[112]; */
	{ (struct TRKOBJINFO*)0x2036, 768, 0, 0, 0xC7, 0, 0, 3, 32, 0 }, /* [118] shapes 82/83; dseg:shapeinfos[113]; */
	{ (struct TRKOBJINFO*)0x2044, 512, 0, 0, 0xC8, 0, 0, 3, 32, 0 }, /* [119] shapes 82/83; dseg:shapeinfos[114]; */
	{ (struct TRKOBJINFO*)0x2052, 256, 0, 0, 0xC9, 0, 0, 3, 32, 0 }, /* [120] shapes 82/83; dseg:shapeinfos[115]; */
	{ (struct TRKOBJINFO*)0x2060, 0, 0, 0, 0xCA, 0, 0, 3, 33, 0 }, /* [121] shapes 84/85; dseg:shapeinfos[116]; */
	{ (struct TRKOBJINFO*)0x206E, 768, 0, 0, 0xCB, 0, 0, 3, 33, 0 }, /* [122] shapes 84/85; dseg:shapeinfos[117]; */
	{ (struct TRKOBJINFO*)0x207C, 512, 0, 0, 0xCC, 0, 0, 3, 33, 0 }, /* [123] shapes 84/85; dseg:shapeinfos[118]; */
	{ (struct TRKOBJINFO*)0x208A, 256, 0, 0, 0xCD, 0, 0, 3, 33, 0 }, /* [124] shapes 84/85; dseg:shapeinfos[119]; */
	{ (struct TRKOBJINFO*)0x1A94, 0, 0, 0, 0, 1, 1, 0, 12, 0 }, /* [125] shapes 52/53; dseg:shapeinfos[10]; */
	{ (struct TRKOBJINFO*)0x1DF8, 0, 0, 0, 0, 1, 1, 0, 6, 0 }, /* [126] shapes 54/55; dseg:shapeinfos[72]; */
	{ (struct TRKOBJINFO*)0x1E14, 768, 0, 0, 0, 1, 1, 0, 6, 0 }, /* [127] shapes 54/55; dseg:shapeinfos[74]; */
	{ (struct TRKOBJINFO*)0x1E30, 512, 0, 0, 0, 1, 1, 0, 6, 0 }, /* [128] shapes 54/55; dseg:shapeinfos[76]; */
	{ (struct TRKOBJINFO*)0x1E4C, 256, 0, 0, 0, 1, 1, 0, 6, 0 }, /* [129] shapes 54/55; dseg:shapeinfos[78]; */
	{ (struct TRKOBJINFO*)0x1E68, 0, 0, 0, 0, 1, 1, 0, 7, 0 }, /* [130] shapes 56/57; dseg:shapeinfos[80]; */
	{ (struct TRKOBJINFO*)0x1E84, 768, 0, 0, 0, 1, 1, 0, 7, 0 }, /* [131] shapes 56/57; dseg:shapeinfos[82]; */
	{ (struct TRKOBJINFO*)0x1EA0, 512, 0, 0, 0, 1, 1, 0, 7, 0 }, /* [132] shapes 56/57; dseg:shapeinfos[84]; */
	{ (struct TRKOBJINFO*)0x1EBC, 256, 0, 0, 0, 1, 1, 0, 7, 0 }, /* [133] shapes 56/57; dseg:shapeinfos[86]; */
	{ (struct TRKOBJINFO*)0x1A24, 0, 0, 0, 14, 1, 0, 0, 0, 0 }, /* [134] shapes 12/13; dseg:shapeinfos[2]; */
	{ (struct TRKOBJINFO*)0x1A40, 512, 0, 0, 14, 1, 0, 0, 0, 0 }, /* [135] shapes 12/13; dseg:shapeinfos[4]; */
	{ (struct TRKOBJINFO*)0x1A32, 256, 0, 0, 15, 1, 0, 0, 0, 0 }, /* [136] shapes 12/13; dseg:shapeinfos[3]; */
	{ (struct TRKOBJINFO*)0x1A4E, 768, 0, 0, 15, 1, 0, 0, 0, 0 }, /* [137] shapes 12/13; dseg:shapeinfos[5]; */
	{ (struct TRKOBJINFO*)0x1A94, 0, 0, 0, 0, 2, 1, 0, 12, 0 }, /* [138] shapes 52/53; dseg:shapeinfos[10]; */
	{ (struct TRKOBJINFO*)0x1DF8, 0, 0, 0, 0, 2, 1, 0, 6, 0 }, /* [139] shapes 54/55; dseg:shapeinfos[72]; */
	{ (struct TRKOBJINFO*)0x1E14, 768, 0, 0, 0, 2, 1, 0, 6, 0 }, /* [140] shapes 54/55; dseg:shapeinfos[74]; */
	{ (struct TRKOBJINFO*)0x1E30, 512, 0, 0, 0, 2, 1, 0, 6, 0 }, /* [141] shapes 54/55; dseg:shapeinfos[76]; */
	{ (struct TRKOBJINFO*)0x1E4C, 256, 0, 0, 0, 2, 1, 0, 6, 0 }, /* [142] shapes 54/55; dseg:shapeinfos[78]; */
	{ (struct TRKOBJINFO*)0x1E68, 0, 0, 0, 0, 2, 1, 0, 7, 0 }, /* [143] shapes 56/57; dseg:shapeinfos[80]; */
	{ (struct TRKOBJINFO*)0x1E84, 768, 0, 0, 0, 2, 1, 0, 7, 0 }, /* [144] shapes 56/57; dseg:shapeinfos[82]; */
	{ (struct TRKOBJINFO*)0x1EA0, 512, 0, 0, 0, 2, 1, 0, 7, 0 }, /* [145] shapes 56/57; dseg:shapeinfos[84]; */
	{ (struct TRKOBJINFO*)0x1EBC, 256, 0, 0, 0, 2, 1, 0, 7, 0 }, /* [146] shapes 56/57; dseg:shapeinfos[86]; */
	{ (struct TRKOBJINFO*)0x1A24, 0, 0, 0, 24, 2, 0, 0, 0, 0 }, /* [147] shapes 12/13; dseg:shapeinfos[2]; */
	{ (struct TRKOBJINFO*)0x1A40, 512, 0, 0, 24, 2, 0, 0, 0, 0 }, /* [148] shapes 12/13; dseg:shapeinfos[4]; */
	{ (struct TRKOBJINFO*)0x1A32, 256, 0, 0, 25, 2, 0, 0, 0, 0 }, /* [149] shapes 12/13; dseg:shapeinfos[3]; */
	{ (struct TRKOBJINFO*)0x1A4E, 768, 0, 0, 25, 2, 0, 0, 0, 0 }, /* [150] shapes 12/13; dseg:shapeinfos[5]; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 74, 0 }, /* [151] shapes 58/59; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 72, 0 }, /* [152] shapes 72/73; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 71, 0 }, /* [153] shapes 51/51; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 73, 0 }, /* [154] shapes 34/35; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 66, 0 }, /* [155] shapes 14/15; */
	{ 0, 512, 0, 0, 0, 0, 0, 0, 66, 0 }, /* [156] shapes 14/15; */
	{ 0, 768, 0, 0, 0, 0, 0, 0, 66, 0 }, /* [157] shapes 14/15; */
	{ 0, 256, 0, 0, 0, 0, 0, 0, 66, 0 }, /* [158] shapes 14/15; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 65, 0 }, /* [159] shapes 0/1; */
	{ 0, 512, 0, 0, 0, 0, 0, 0, 65, 0 }, /* [160] shapes 0/1; */
	{ 0, 768, 0, 0, 0, 0, 0, 0, 65, 0 }, /* [161] shapes 0/1; */
	{ 0, 256, 0, 0, 0, 0, 0, 0, 65, 0 }, /* [162] shapes 0/1; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 68, 0 }, /* [163] shapes 20/21; */
	{ 0, 512, 0, 0, 0, 0, 0, 0, 68, 0 }, /* [164] shapes 20/21; */
	{ 0, 768, 0, 0, 0, 0, 0, 0, 68, 0 }, /* [165] shapes 20/21; */
	{ 0, 256, 0, 0, 0, 0, 0, 0, 68, 0 }, /* [166] shapes 20/21; */
	{ 0, 0, 0, 0, 0, 0xFF, 0, 0, 69, 0 }, /* [167] shapes 94/95; */
	{ 0, 512, 0, 0, 0, 0xFF, 0, 0, 69, 0 }, /* [168] shapes 94/95; */
	{ 0, 768, 0, 0, 0, 0xFF, 0, 0, 69, 0 }, /* [169] shapes 94/95; */
	{ 0, 256, 0, 0, 0, 0xFF, 0, 0, 69, 0 }, /* [170] shapes 94/95; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 70, 0 }, /* [171] shapes 96/97; */
	{ 0, 512, 0, 0, 0, 0, 0, 0, 70, 0 }, /* [172] shapes 96/97; */
	{ 0, 768, 0, 0, 0, 0, 0, 0, 70, 0 }, /* [173] shapes 96/97; */
	{ 0, 256, 0, 0, 0, 0, 0, 0, 70, 0 }, /* [174] shapes 96/97; */
	{ 0, 0, 0, 0, 0, 0xFF, 0, 0, 67, 0 }, /* [175] shapes 98/99; */
	{ 0, 512, 0, 0, 0, 0xFF, 0, 0, 67, 0 }, /* [176] shapes 98/99; */
	{ 0, 768, 0, 0, 0, 0xFF, 0, 0, 67, 0 }, /* [177] shapes 98/99; */
	{ 0, 256, 0, 0, 0, 0xFF, 0, 0, 67, 0 }, /* [178] shapes 98/99; */
	{ (struct TRKOBJINFO*)0x1A40, 512, 0, 0, 4, 0, 0, 0, 0, 0 }, /* [179] shapes 12/13; dseg:shapeinfos[4]; */
	{ (struct TRKOBJINFO*)0x1A32, 256, 0, 0, 5, 0, 0, 0, 0, 0 }, /* [180] shapes 12/13; dseg:shapeinfos[3]; */
	{ (struct TRKOBJINFO*)0x1A4E, 768, 0, 0, 5, 0, 0, 0, 0, 0 }, /* [181] shapes 12/13; dseg:shapeinfos[5]; */
	{ (struct TRKOBJINFO*)0x1BC8, 0, 0, 0, 0, 0, 1, 0, 1, 0 }, /* [182] shapes 28/29; dseg:shapeinfos[32]; */
	{ (struct TRKOBJINFO*)0x1BBA, 768, 0, 0, 0, 0, 1, 0, 1, 0 }, /* [183] shapes 28/29; dseg:shapeinfos[31]; */
	{ (struct TRKOBJINFO*)0x1BAC, 512, 0, 0, 0, 0, 1, 0, 1, 0 }, /* [184] shapes 28/29; dseg:shapeinfos[30]; */
	{ (struct TRKOBJINFO*)0x1BD6, 256, 0, 0, 0, 0, 1, 0, 1, 0 }, /* [185] shapes 28/29; dseg:shapeinfos[33]; */
	{ (struct TRKOBJINFO*)0x1BC8, 0, 0, 0, 0, 1, 1, 0, 1, 0 }, /* [186] shapes 28/29; dseg:shapeinfos[32]; */
	{ (struct TRKOBJINFO*)0x1BBA, 768, 0, 0, 0, 1, 1, 0, 1, 0 }, /* [187] shapes 28/29; dseg:shapeinfos[31]; */
	{ (struct TRKOBJINFO*)0x1BAC, 512, 0, 0, 0, 1, 1, 0, 1, 0 }, /* [188] shapes 28/29; dseg:shapeinfos[30]; */
	{ (struct TRKOBJINFO*)0x1BD6, 256, 0, 0, 0, 1, 1, 0, 1, 0 }, /* [189] shapes 28/29; dseg:shapeinfos[33]; */
	{ (struct TRKOBJINFO*)0x1BC8, 0, 0, 0, 0, 2, 1, 0, 1, 0 }, /* [190] shapes 28/29; dseg:shapeinfos[32]; */
	{ (struct TRKOBJINFO*)0x1BBA, 768, 0, 0, 0, 2, 1, 0, 1, 0 }, /* [191] shapes 28/29; dseg:shapeinfos[31]; */
	{ (struct TRKOBJINFO*)0x1BAC, 512, 0, 0, 0, 2, 1, 0, 1, 0 }, /* [192] shapes 28/29; dseg:shapeinfos[30]; */
	{ (struct TRKOBJINFO*)0x1BD6, 256, 0, 0, 0, 2, 1, 0, 1, 0 }, /* [193] shapes 28/29; dseg:shapeinfos[33]; */
	{ (struct TRKOBJINFO*)0x1C1C, 0, 0, 0, 0xDE, 0, 0, 0, 19, 0 }, /* [194] shapes 70/71; dseg:shapeinfos[38]; */
	{ (struct TRKOBJINFO*)0x1C46, 768, 0, 0, 0xDF, 0, 0, 0, 19, 0 }, /* [195] shapes 70/71; dseg:shapeinfos[41]; */
	{ (struct TRKOBJINFO*)0x1C2A, 512, 0, 0, 0xE0, 0, 0, 0, 19, 0 }, /* [196] shapes 70/71; dseg:shapeinfos[39]; */
	{ (struct TRKOBJINFO*)0x1C38, 256, 0, 0, 0xE1, 0, 0, 0, 19, 0 }, /* [197] shapes 70/71; dseg:shapeinfos[40]; */
	{ 0, 0, 0, 0, 0, 0, 1, 3, 32, 0 }, /* [198] shapes 88/-1; */
	{ 0, 768, 0, 0, 0, 0, 1, 3, 32, 0 }, /* [199] shapes 88/-1; */
	{ 0, 512, 0, 0, 0, 0, 1, 3, 32, 0 }, /* [200] shapes 88/-1; */
	{ 0, 256, 0, 0, 0, 0, 1, 3, 32, 0 }, /* [201] shapes 88/-1; */
	{ 0, 0, 0, 0, 0, 0, 1, 3, 33, 0 }, /* [202] shapes 89/-1; */
	{ 0, 768, 0, 0, 0, 0, 1, 3, 33, 0 }, /* [203] shapes 89/-1; */
	{ 0, 512, 0, 0, 0, 0, 1, 3, 33, 0 }, /* [204] shapes 89/-1; */
	{ 0, 256, 0, 0, 0, 0, 1, 3, 33, 0 }, /* [205] shapes 89/-1; */
	{ 0, 0, 0, 0, 0, 0, 1, 1, 27, 0 }, /* [206] shapes 90/-1; */
	{ 0, 256, 0, 0, 0, 0, 1, 2, 27, 0 }, /* [207] shapes 90/-1; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 28, 0 }, /* [208] shapes 104/-1; */
	{ 0, 256, 0, 0, 0, 0, 1, 0, 28, 0 }, /* [209] shapes 104/-1; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 30, 0 }, /* [210] shapes 105/-1; */
	{ 0, 256, 0, 0, 0, 0, 0, 0, 30, 0 }, /* [211] shapes 105/-1; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0 }, /* [212] shapes 49/49; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0 }, /* [213] shapes 50/50; */
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0 }, /* [214] shapes 106/107; */
};
static const int16_t trkObjectList_shapeidx[215][2] = {
	{30,30}, {12,13}, {126,128}, {127,129}, {30,31}, {30,31}, {38,39}, {38,39},
	{38,39}, {38,39}, {32,33}, {32,33}, {32,33}, {32,33}, {30,31}, {30,31},
	{38,39}, {38,39}, {38,39}, {38,39}, {32,33}, {32,33}, {32,33}, {32,33},
	{30,31}, {30,31}, {38,39}, {38,39}, {38,39}, {38,39}, {32,33}, {32,33},
	{32,33}, {32,33}, {10,11}, {10,11}, {24,25}, {24,25}, {24,25}, {24,25},
	{26,27}, {26,27}, {26,27}, {26,27}, {16,17}, {16,17}, {16,17}, {16,17},
	{60,61}, {60,61}, {60,61}, {60,61}, {4,5}, {4,5}, {4,5}, {4,5},
	{2,3}, {2,3}, {2,3}, {2,3}, {8,9}, {6,7}, {6,7}, {8,9},
	{18,19}, {18,19}, {36,37}, {36,37}, {22,23}, {22,23}, {74,75}, {74,75},
	{74,75}, {74,75}, {52,53}, {54,55}, {54,55}, {54,55}, {54,55}, {56,57},
	{56,57}, {56,57}, {56,57}, {100,101}, {100,101}, {102,103}, {102,103}, {62,63},
	{62,63}, {62,63}, {62,63}, {64,65}, {64,65}, {64,65}, {64,65}, {66,67},
	{66,67}, {66,67}, {66,67}, {68,69}, {68,69}, {70,71}, {70,71}, {70,71},
	{70,71}, {76,77}, {76,77}, {76,77}, {76,77}, {78,79}, {78,79}, {86,87},
	{86,87}, {86,87}, {86,87}, {80,81}, {80,81}, {82,83}, {82,83}, {82,83},
	{82,83}, {84,85}, {84,85}, {84,85}, {84,85}, {52,53}, {54,55}, {54,55},
	{54,55}, {54,55}, {56,57}, {56,57}, {56,57}, {56,57}, {12,13}, {12,13},
	{12,13}, {12,13}, {52,53}, {54,55}, {54,55}, {54,55}, {54,55}, {56,57},
	{56,57}, {56,57}, {56,57}, {12,13}, {12,13}, {12,13}, {12,13}, {58,59},
	{72,73}, {51,51}, {34,35}, {14,15}, {14,15}, {14,15}, {14,15}, {0,1},
	{0,1}, {0,1}, {0,1}, {20,21}, {20,21}, {20,21}, {20,21}, {94,95},
	{94,95}, {94,95}, {94,95}, {96,97}, {96,97}, {96,97}, {96,97}, {98,99},
	{98,99}, {98,99}, {98,99}, {12,13}, {12,13}, {12,13}, {28,29}, {28,29},
	{28,29}, {28,29}, {28,29}, {28,29}, {28,29}, {28,29}, {28,29}, {28,29},
	{28,29}, {28,29}, {70,71}, {70,71}, {70,71}, {70,71}, {88,-1}, {88,-1},
	{88,-1}, {88,-1}, {89,-1}, {89,-1}, {89,-1}, {89,-1}, {90,-1}, {90,-1},
	{104,-1}, {104,-1}, {105,-1}, {105,-1}, {49,49}, {50,50}, {106,107},
};

/* dseg 0x3E3CA: 19 entries x 14 DOS bytes, transcribed from dseg.asm.
   ss_shapePtr/ss_loShapePtr are patched to &game3dshapes[i] at startup
   from sceneshapes2_shapeidx[] (misaligned-pointer-relocation workaround -- see tools/extract_dseg_tables.py). */
struct TRACKOBJECT sceneshapes2[19] = {
	{ 0, 0, 0, 0, 0, 0, 0, 0, 0xFF, 0 }, /* [0] shapes 108/109; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [1] shapes 45/45; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [2] shapes 44/44; */
	{ 0, 768, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [3] shapes 44/44; */
	{ 0, 512, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [4] shapes 44/44; */
	{ 0, 256, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [5] shapes 44/44; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [6] shapes 43/43; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [7] shapes 42/42; */
	{ 0, 768, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [8] shapes 42/42; */
	{ 0, 512, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [9] shapes 42/42; */
	{ 0, 256, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [10] shapes 42/42; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [11] shapes 41/41; */
	{ 0, 768, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [12] shapes 41/41; */
	{ 0, 512, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [13] shapes 41/41; */
	{ 0, 256, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [14] shapes 41/41; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [15] shapes 40/40; */
	{ 0, 768, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [16] shapes 40/40; */
	{ 0, 512, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [17] shapes 40/40; */
	{ 0, 256, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [18] shapes 40/40; */
};
static const int16_t sceneshapes2_shapeidx[19][2] = {
	{108,109}, {45,45}, {44,44}, {44,44}, {44,44}, {44,44}, {43,43}, {42,42},
	{42,42}, {42,42}, {42,42}, {41,41}, {41,41}, {41,41}, {41,41}, {40,40},
	{40,40}, {40,40}, {40,40},
};

/* dseg 0x3E4D4: 13 entries x 14 DOS bytes, transcribed from dseg.asm.
   ss_shapePtr/ss_loShapePtr are patched to &game3dshapes[i] at startup
   from sceneshapes3_shapeidx[] (misaligned-pointer-relocation workaround -- see tools/extract_dseg_tables.py). */
struct TRACKOBJECT sceneshapes3[13] = {
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [0] shapes 112/112; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [1] shapes 113/113; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [2] shapes 114/114; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [3] shapes 115/115; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [4] shapes 116/116; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [5] shapes 117/117; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [6] shapes 118/118; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [7] shapes 119/119; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [8] shapes 120/120; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [9] shapes 121/121; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [10] shapes 122/122; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [11] shapes 123/123; */
	{ 0, 0, 0, 0, 0, 0, 1, 0, 0xFF, 0 }, /* [12] shapes 110/110; */
};
static const int16_t sceneshapes3_shapeidx[13][2] = {
	{112,112}, {113,113}, {114,114}, {115,115}, {116,116}, {117,117}, {118,118}, {119,119},
	{120,120}, {121,121}, {122,122}, {123,123}, {110,110},
};

/* Patch the pack(1)-misaligned shape pointer fields at startup. */
__attribute__((constructor)) static void rdata_fixup_trackobject_shapes(void)
{
	size_t i;
	for (i = 0; i < sizeof(trkObjectList) / sizeof(trkObjectList[0]); i++) {
		if (trkObjectList_shapeidx[i][0] >= 0)
			trkObjectList[i].ss_shapePtr = &game3dshapes[trkObjectList_shapeidx[i][0]];
		if (trkObjectList_shapeidx[i][1] >= 0)
			trkObjectList[i].ss_loShapePtr = &game3dshapes[trkObjectList_shapeidx[i][1]];
	}
	for (i = 0; i < sizeof(sceneshapes2) / sizeof(sceneshapes2[0]); i++) {
		if (sceneshapes2_shapeidx[i][0] >= 0)
			sceneshapes2[i].ss_shapePtr = &game3dshapes[sceneshapes2_shapeidx[i][0]];
		if (sceneshapes2_shapeidx[i][1] >= 0)
			sceneshapes2[i].ss_loShapePtr = &game3dshapes[sceneshapes2_shapeidx[i][1]];
	}
	for (i = 0; i < sizeof(sceneshapes3) / sizeof(sceneshapes3[0]); i++) {
		if (sceneshapes3_shapeidx[i][0] >= 0)
			sceneshapes3[i].ss_shapePtr = &game3dshapes[sceneshapes3_shapeidx[i][0]];
		if (sceneshapes3_shapeidx[i][1] >= 0)
			sceneshapes3[i].ss_loShapePtr = &game3dshapes[sceneshapes3_shapeidx[i][1]];
	}
}

/* ------------------------------------------------------------------ */
/* Group 3: state variables (zero-initialized; sizes from dseg.asm)    */
/* ------------------------------------------------------------------ */

struct GAMESTATE state;              /* dseg 0x44352: 1120 bytes zero */
struct SIMD simd_player;             /* dseg 0x45E5E: 776 DOS bytes zero */
struct SIMD simd_opponent;           /* dseg 0x45146: 776 DOS bytes zero */
void far* gameresptr;      /* dseg: GAME.PRE, set in main_native */
char idle_expired;         /* dseg: attract mode has taken over */
char passed_security = 1;  /* dseg. Set once the copy-protection question
                            * is answered; this port asks nothing, so the
                            * warning must not fire. */
char textresprefix = 'e'; /* restunts.c:1268 - the language prefix */
struct GAMEINFO gameconfig;          /* dseg 0x449C2: 26 bytes zero */

/* dseg 0x44D62 / 0x45338: dd 0 -- far POINTERS to the track element/terrain
 * grids (the grids themselves live in far heap track data, not in dseg). */
uint8_t far* td14_elem_map_main;
uint8_t far* td15_terr_map_main;

struct TRANSFORMEDSHAPE3D currenttransshape[29]; /* dseg 0x44030: 29*20 DOS bytes zero */
struct TRANSFORMEDSHAPE3D* curtransshape_ptr;    /* dseg 0x46425: dw 0 */

struct VECTOR carshapevec;       /* dseg 0x42D2A */
struct VECTOR carshapevec2;      /* dseg 0x42D30 */
struct VECTOR carshapevecs[6];   /* dseg 0x442A6 */
struct VECTOR carshapevecs2[6];  /* dseg 0x442CA */
struct VECTOR carshapevecs3[6];  /* dseg 0x442EE */
struct VECTOR carshapevecs4[6];  /* dseg 0x44312 */
struct VECTOR oppcarshapevec;    /* dseg 0x42D55 */
struct VECTOR oppcarshapevec2;   /* dseg 0x42D5B */
struct VECTOR oppcarshapevecs[6];  /* dseg 0x44ADE */
struct VECTOR oppcarshapevecs2[6]; /* dseg 0x44B02 */
struct VECTOR oppcarshapevecs3[6]; /* dseg 0x44B26 */
struct VECTOR oppcarshapevecs4[6]; /* dseg 0x44B4A */
int16_t word_443E8[5];           /* dseg 0x443E8: dw + 4 db pairs zero */
int16_t word_4448A[5];           /* dseg 0x4448A: dw + 4 db pairs zero */

char backlights_paint_override;  /* dseg 0x45388: db 0 (+1 pad byte) */

/* dseg 0x3E70A: mutable resource-name template for car shape loading. */
/* dseg: "stxxx",0 — but shape3d_load_car_shapes writes indices [2..5],
 * overwriting the NUL; in DOS the next dseg byte (unk_3E710) is 0 and acts
 * as the terminator. Reproduce that guarantee with an explicit extra byte. */
char aStxxx[7] = "stxxx";

struct RECTANGLE select_rect_rc; /* dseg 0x4157E: 8 bytes zero */
uint16_t select_rect_param;      /* dseg 0x415A2: dw 0 */

struct MATRIX mat_temp;      /* dseg 0x4643C */
struct MATRIX mat_rot_temp;  /* dseg 0x46428 */
struct MATRIX mat_x_rot;     /* dseg 0x46476 */
struct MATRIX mat_y_rot;     /* dseg 0x44D26 */
struct MATRIX mat_z_rot;     /* dseg 0x4392E */
struct MATRIX mat_y0;        /* dseg 0x41B02 */
struct MATRIX mat_y100;      /* dseg 0x4156C */
struct MATRIX mat_y200;      /* dseg 0x4155A */
struct MATRIX mat_y300;      /* dseg 0x41586 */
uint16_t mat_y_rot_angle = 0xFFFF; /* dseg 0x3EFF6: dw -1 */
struct MATRIX mat_unk;       /* dseg 0x44240 */
struct MATRIX mat_unk2;      /* dseg 0x41434 */
struct MATRIX mat_planetmp;  /* dseg 0x41446 */

int32_t sin80;    /* dseg 0x41B2F: dd 0 */
int32_t cos80;    /* dseg 0x41B2B: dd 0 */
int32_t sin80_2;  /* dseg 0x41B37: dd 0 (dseg block is followed by 576
                   * unlabeled zero bytes never referenced by the renderer) */
int32_t cos80_2;  /* dseg 0x41B33: dd 0 */

struct VECTOR vec_unk2;             /* dseg 0x44FCA */
struct VECTOR vec_planerotopresult; /* dseg 0x44FD0 */
int16_t terrainHeight;   /* dseg 0x449F4: dw 0 */
int16_t planindex;       /* dseg 0x44DC8: dw 0 */
int16_t planindex_copy;  /* dseg 0x44FDA: dw 0 */
struct PLANE far* planptr;         /* dseg 0x4533C: dd 0 */
struct PLANE far* current_planptr; /* dseg 0x44D7E: dd 0 */

char byte_4392C;    /* dseg 0x4392C: db 0 (+1 pad byte) */
/* dseg 0x4393C: db 0.  The attract-mode autopilot's state machine, driven
 * by update_gamestate's game_replay_mode == 1 branch (seg001.asm 4501+). */
uint8_t byte_4393C;
uint8_t byte_4393D; /* dseg 0x4393D: db 0 */
/* dseg 0x449DA: db 0.  Latch that stops update_gamestate's frame-rate
 * autotune from firing more than once (seg001.asm 4478). */
uint8_t byte_449DA;
uint8_t byte_45514; /* not found in dseg.asm; zero-init (only referenced in
                     * a commented-out asm block in shape3d.c) */
uint16_t word_40ECE;      /* dseg 0x40ECE: dw 0 */

uint16_t transshapenumverts;            /* dseg 0x41B27 */
uint8_t far* transshapeprimitives;      /* dseg 0x41B17: dd 0 */
struct VECTOR far* transshapeverts;     /* dseg 0x41B29+... dseg 0x41B2B area: dd 0 */
uint16_t transshapenumpaints;           /* dseg 0x41AF7 */
uint8_t transshapematerial;             /* dseg 0x41B21: db 0 (+1 pad) */
uint8_t transshapeflags;                /* dseg 0x41B13: db 0 (+1 pad) */
struct RECTANGLE* transshaperectptr;    /* dseg 0x41B1F: dw 0 */
uint8_t transshapenumvertscopy;         /* dseg 0x449F8: db 0 (+1 pad) */
char far* transshapeprimptr;            /* dseg 0x41B0B: dd 0 */
char far* transshapepolyinfo;           /* dseg 0x415A0 area: dd 0 */
char transprimitivepaintjob;            /* dseg 0x41B39: db 0 (+1 pad) */
uint8_t far* transshapeprimindexptr;    /* dseg 0x41B1B: dd 0 */
/* transshapepolyinfopts is defined in shape3d.c -- not defined here. */

int16_t far* polyinfoptrs[0x190];       /* dseg 0x4172E: 400 dd 0 (dseg block
                                         * has 6 trailing unlabeled zero bytes) */
struct POINT2D* polyvertpointptrtab[10]; /* dseg 0x41AF9: 10 dw 0 (+2 pad) */

/* dseg 0x40ED6: 0x190-entry poly linked list; element [0x190] is the dseg
 * word word_411F6 that immediately follows it (see sdl/main.cpp word_40ED6). */
int16_t poly_linked_list_40ED6[0x190 + 1];
uint16_t poly_linklist_40ED6_iter1;  /* dseg 0x4393A */
uint16_t poly_linklist_40ED6_iter2;  /* dseg 0x443F2 */
uint16_t poly_linklist_40ED6_iter3;  /* dseg 0x453A6 */
uint16_t poly_linklist_40ED6_iter4;  /* dseg 0x45E30 */
uint16_t polyinfonumpolys;           /* dseg 0x44252: dw 0 */
char far* polyinfoptr;               /* dseg 0x415A4: dd 0 */
uint16_t polyinfoptrnext;            /* dseg 0x41AF5: dw 0 */

int16_t transformedshape_zarray[29];  /* dseg 0x45340: dw + db, 58 bytes zero */
int16_t transformedshape_indices[29]; /* dseg 0x45E68 area: 58 bytes zero */
char transformedshape_arg2array[30];  /* dseg 0x45A26: 30 bytes zero */
char transformedshape_counter;        /* dseg 0x45E26: db 0 (+1 pad) */

/* dseg 0x44A04..0x44A7B: fifteen contiguous dirty-rectangles indexed from
 * rect_unk[0..14] by frame.c.  The individually-named rects are the SAME
 * memory (dseg labels inside the block), so they are emitted as assembler
 * aliases into the array rather than separate objects:
 *   +0x00 rect_unk[0]  (rect_unk)      +0x28 rect_unk[5]  (rect_skybox)
 *   +0x08 rect_unk[1]  (rect_unk2)     +0x30 rect_unk[6]  (rect_unk11)
 *   +0x10 rect_unk[2]  (rect_unk6)     +0x38 rect_unk[7]  (rect_unk9)
 *   +0x18 rect_unk[3]  (rect_unk12)    +0x40..0x77 rect_unk[8..14] (unnamed)
 *   +0x20 rect_unk[4]  (rect_unk15)
 * The explicit initializer keeps rect_unk out of the common section so the
 * .set aliases resolve at assembly time (Mach-O has no attribute((alias))). */
struct RECTANGLE rect_unk[15] = {{0, 0, 0, 0}};
__asm__(
	".globl _rect_unk2\n"  ".set _rect_unk2,  _rect_unk + 0x08\n"
	".globl _rect_unk6\n"  ".set _rect_unk6,  _rect_unk + 0x10\n"
	".globl _rect_unk12\n" ".set _rect_unk12, _rect_unk + 0x18\n"
	".globl _rect_unk15\n" ".set _rect_unk15, _rect_unk + 0x20\n"
	".globl _rect_unk11\n" ".set _rect_unk11, _rect_unk + 0x30\n"
	".globl _rect_unk9\n"  ".set _rect_unk9,  _rect_unk + 0x38\n"
);

struct RECTANGLE rect_array_unk[15];  /* dseg 0x453AE: 120 bytes zero (block
                                       * has 4 trailing unlabeled zero bytes) */
struct RECTANGLE rect_array_unk2[15]; /* dseg 0x45992: 120 bytes zero */

/* dseg 0x3EFF8: inside-out rect, ready for min/max accumulation. */
struct RECTANGLE cliprect_unk = { 9999, -1, 9999, -1 };

struct RECTANGLE* rectptr_unk;   /* dseg 0x3B7F6: dw 0 */
struct RECTANGLE* rectptr_unk2;  /* dseg 0x3B7F4: dw 0 */

/* dseg 0x3B8EE / 0x3B8F0 / 0x3B8F2 area: F1..F4 custom camera defaults. */
int16_t custom_camera_distance = 210;
int16_t custom_camera_azimuth_angle = 464;
int16_t custom_camera_elevation_angle = 80;

char cameramode;          /* dseg 0x3B8F5 */
uint8_t detail_level;     /* dseg 0x3B8FA */
uint8_t game_replay_mode; /* dseg 0x45E34: db 0 (+1 pad) */
char followOpponentFlag;  /* dseg 0x46353: db 0 (+1 pad) */
uint16_t elapsed_time1;   /* dseg 0x45A3B area: dw 0 */
uint16_t elapsed_time2;   /* dseg 0x42D54 area: dw 0 */
int16_t f36f40_whlData = 9999; /* dseg 0x3BE14: dw 9999 */
int16_t pState_minusRotate_z_2; /* dseg 0x44FD6 */
int16_t pState_minusRotate_x_2; /* dseg 0x44FD8 area */
int16_t pState_minusRotate_y_2; /* dseg 0x44FDA area */
int16_t pState_f36Mminf40sar2;  /* dseg 0x44FDC area */
/* dseg 0x46358. The original is a text buffer here, not a single byte:
 * format_frame_as_string() writes "M:SS" (and optionally ".cc") into it.
 * Declaring it as one char let that write run into the next global. */
char resID_byte1[32];
int16_t run_game_random;  /* dseg 0x42D6D: dw 0 */
int16_t video_flag2_is1;  /* dseg 0x44DCC: dw 0 */
int16_t video_flag5_is0;  /* dseg 0x46426 area: 2 db zero */
/* dseg 35601: dw 0, and seg031.asm:236 sets it to 1 as part of bringing the
 * MCGA mode up. It is a multiplier on shape widths (`imul video_flag1_is1`
 * in seg000 x4, seg005 x3, seg009 x4), so leaving it 0 collapses every one
 * of those to zero width. game_init sets it, as it does the other three. */
int16_t video_flag1_is1;
char startcol2;           /* dseg 0x449BC */
char startrow2;           /* dseg 0x449BF */
int16_t terrainrows[30];  /* dseg 0x44230 area: 30 dw zero */
int16_t trackrows[30];    /* dseg 0x45DE2 area: 30 dw zero */
int16_t trackpos[30];     /* dseg 0x438F2 area: 30 dw zero */
int16_t trackpos2[30];    /* dseg 0x42D36 area: 30 dw zero */
int16_t trackcenterpos[30];  /* dseg 0x46016 area: 30 dw zero */
int16_t trackcenterpos2[30]; /* dseg 0x45E96 area: 30 dw zero */
int16_t track_angle;      /* dseg 0x4538A: dw 0 */
int16_t elem_xCenter;     /* dseg 0x449EE area: dw 0 */
int16_t elem_zCenter;     /* dseg 0x449F6 area: dw 0 */
char hillFlag;            /* dseg 0x449BD */
void far* sdgame2shapes[5]; /* dseg 0x45E44 area: 5 dd zero */
void far* fontdefptr;      /* dseg: the default (non-LED) font */
void far* fontledresptr;  /* dseg 0x45A2E area: dd 0 (+4 unlabeled bytes) */
void far* fontnptr;       /* dseg: FONTN.FNT, the narrow face the high-score
                           * table's four columns and the opponent menu's
                           * description use (seg000 highscore_text_unk,
                           * run_opponent_menu). Set in main_native. */
void far* mainresptr;     /* dseg: MAIN.RES, the language file. Set likewise. */
void far* miscptr;        /* dseg: MISC.PRE, the button labels. */
int16_t dialog_fnt_colour = 15; /* dseg 0x44D9A area: dw 15 */
int16_t meter_needle_color;     /* dseg 0x4653C: dw 0, = dialog_fnt_colour */
int16_t word_463D6;       /* dseg 0x463D6: dw 0 */

/* ------------------------------------------------------------------ */
/* Group 4: material list pointers (from sdl/main.cpp, with the        */
/* pointer types/names used by externs.h in this port)                 */
/* ------------------------------------------------------------------ */

int16_t* material_clrlist_ptr = material_color_list;
int16_t* material_clrlist2_ptr = material_color_list;
int16_t* material_patlist_ptr = material_pattern_list;
int16_t* material_patlist2_ptr = material_pattern2_list;

int16_t* material_clrlist_ptr_cpy;
int16_t* material_clrlist2_ptr_cpy;
int16_t* material_patlist_ptr_cpy;
int16_t* material_patlist2_ptr_cpy;
uint16_t someZeroVideoConst;

void copy_material_list_pointers(int16_t* m1, int16_t* m2, int16_t* m3,
                                 int16_t* m4, uint16_t unk) {
	material_clrlist_ptr_cpy = m1;
	material_clrlist2_ptr_cpy = m2;
	material_patlist_ptr_cpy = m3;
	material_patlist2_ptr_cpy = m4;
	someZeroVideoConst = unk;
}

/* ================================================================== */
/* Second pass: dseg symbols referenced by rframe_helpers.c            */
/* (build_track_object, skybox_op).  Types follow the extern           */
/* declarations in rframe_helpers.c; values/sizes from dseg.asm.       */
/* ================================================================== */

/* --- skybox state (all dw 0 in dseg) --- */
int16_t skybox_current;    /* dseg 0x43930 */
int16_t skybox_wat_color;  /* dseg: water colour, from material_clrlist[0xC8] */
int16_t skybox_sky_color;  /* dseg 0x45886 */
int16_t skybox_grd_color;  /* dseg 0x44A88 */
int16_t word_454CE;        /* dseg 0x454CE: skybox bitmap slice height */
int16_t skybox_ptr1;       /* dseg 0x4538C */
int16_t skybox_ptr2;       /* dseg 0x4538E */
int16_t skybox_ptr3;       /* dseg 0x45390 */
int16_t skybox_ptr4;       /* dseg 0x45392 */
void far* skyboxes[4];     /* dseg 0x45E36: 4 dd 0 (far SHAPE2D bitmap ptrs) */

/* rect_skybox is dseg 0x44A2C = rect_unk + 0x28 (element [5] of the
 * 15-rect dirty-rect block defined above) -- alias, not a new object. */
__asm__(
	".globl _rect_skybox\n" ".set _rect_skybox, _rect_unk + 0x28\n"
);

struct RECTANGLE rect_array_unk3[45]; /* dseg 0x44DCE: 360 bytes zero */
char rect_array_unk3_length;          /* dseg 0x46023: db 0 */
char rect_array_unk_indices[15];      /* dseg 0x45394: 15 db zero */

int16_t terrainpos[30];        /* dseg 0x4531E: 30 dw zero */
int16_t terraincenterpos[30];  /* dseg 0x42D08 area: 30 dw zero */
int16_t video_flag3_isFFFF;    /* dseg 0x454C6 area: dw 0 */
char byte_454A4;               /* dseg 0x454A4: db 0 (+1 pad) */

/* --- wall/element scratch state (build_track_object) --- */
int16_t wallindex;        /* dseg 0x441F2 area: dw 0 */
int16_t wallHeight;       /* dseg 0x4531C: dw 0 */
int16_t elRdWallRelated;  /* dseg 0x449A2 area: dw 0 */
int16_t wallOrientation;  /* dseg 0x45E2E area: dw 0 */
int16_t wallStartX;       /* dseg 0x42D69 area: dw 0 */
int16_t wallStartZ;       /* dseg 0x42D71 area: dw 0 */
int16_t far* wallptr;     /* dseg 0x46460 area: dd 0 */
char corkFlag;            /* dseg 0x44D64 area: db 0 */
char current_surf_type;   /* dseg 0x44D65 area: db 0 (4=grass, 5=water) */

/* --- track-element geometry bounds cluster, dseg 0x3E58A..0x3E63F ---
 * One CONTIGUOUS 182-byte block of 91 int16 words.  dseg.asm interleaves
 * labels inside it and build_track_object indexes ACROSS the label
 * boundaries (e.g. highEntrXInnBounds0[di] with di=1..6 reads the words
 * labeled highEntrXInnBounds1; loopSurface_maxZ is the apex word INSIDE the
 * Z profile array loopSurface_ZBounds0[] = {0,224,389,449,389,224,0}).
 * It is therefore defined as a single backing array under the first label,
 * with every interior dseg label emitted as an assembler alias at its exact
 * byte offset (same technique as rect_unk above). */
int16_t loopSurface_ZBounds0[91] = {
	/* +0x00 loopSurface_ZBounds0   */ 0,
	/* +0x02 loopSurface_ZBounds1   */ 224, 389,
	/* +0x06 loopSurface_maxZ       */ 449, 389, 224, 0,
	/* +0x0E loopSurface_XBounds0   */ -400,
	/* +0x10 loopSurface_XBounds1   */ -400, -352, -304, -270, -235, -200,
	                                   0, 135, 299, 524, 749, 914, 975,
	/* +0x2A loopBase_ZBounds0      */ 0,
	/* +0x2C loopBase_ZBounds1      */ 178, 360, 536, 704, 868, 2000,
	/* +0x38 loopBae_InnXBounds0    */ 0,
	/* +0x3A loopBase_InnXBounds1   */ -20, -40, -60, -80, -100, -120,
	/* +0x46 loopBase_OutXBounds0   */ 400,
	/* +0x48 loopBase_OutXBounds1   */ 361, 320, 276, 226, 174, 120,
	/* +0x54 bkRdEntr_triang_zAdjust*/ -251, -84, 84, 251,
	/* +0x5C corkLR_negZBound       */ 0, -94, -187, -280, -373, -466,
	                                   -559, -652, -745, -838, -931, -1024,
	/* +0x74 corkLR_posZBound       */ 0, 1024, 931, 838, 745, 652,
	                                   559, 466, 373, 280, 187, 94,
	/* +0x8C highEntrZBounds0       */ -512,
	/* +0x8E highEntrZBounds1       */ -334, -168, 0, 168, 334, 1000,
	/* +0x9A highEntrXInnBounds0    */ 0,
	/* +0x9C highEntrXInnBounds1    */ 0, 0, 0, 0, 120, 120,
	/* +0xA8 highEntrXOutBounds0    */ 120,
	/* +0xAA highEntrXOutBounds1    */ 168, 216, 264, 312, 360, 360,
};
_Static_assert(sizeof(loopSurface_ZBounds0) == 0xB6, "bounds cluster is 182 bytes");
__asm__(
	".globl _loopSurface_ZBounds1\n"    ".set _loopSurface_ZBounds1,    _loopSurface_ZBounds0 + 0x02\n"
	".globl _loopSurface_maxZ\n"        ".set _loopSurface_maxZ,        _loopSurface_ZBounds0 + 0x06\n"
	".globl _loopSurface_XBounds0\n"    ".set _loopSurface_XBounds0,    _loopSurface_ZBounds0 + 0x0E\n"
	".globl _loopSurface_XBounds1\n"    ".set _loopSurface_XBounds1,    _loopSurface_ZBounds0 + 0x10\n"
	".globl _loopBase_ZBounds0\n"       ".set _loopBase_ZBounds0,       _loopSurface_ZBounds0 + 0x2A\n"
	".globl _loopBase_ZBounds1\n"       ".set _loopBase_ZBounds1,       _loopSurface_ZBounds0 + 0x2C\n"
	".globl _loopBae_InnXBounds0\n"     ".set _loopBae_InnXBounds0,     _loopSurface_ZBounds0 + 0x38\n"
	".globl _loopBase_InnXBounds1\n"    ".set _loopBase_InnXBounds1,    _loopSurface_ZBounds0 + 0x3A\n"
	".globl _loopBase_OutXBounds0\n"    ".set _loopBase_OutXBounds0,    _loopSurface_ZBounds0 + 0x46\n"
	".globl _loopBase_OutXBounds1\n"    ".set _loopBase_OutXBounds1,    _loopSurface_ZBounds0 + 0x48\n"
	".globl _bkRdEntr_triang_zAdjust\n" ".set _bkRdEntr_triang_zAdjust, _loopSurface_ZBounds0 + 0x54\n"
	".globl _corkLR_negZBound\n"        ".set _corkLR_negZBound,        _loopSurface_ZBounds0 + 0x5C\n"
	".globl _corkLR_posZBound\n"        ".set _corkLR_posZBound,        _loopSurface_ZBounds0 + 0x74\n"
	".globl _highEntrZBounds0\n"        ".set _highEntrZBounds0,        _loopSurface_ZBounds0 + 0x8C\n"
	".globl _highEntrZBounds1\n"        ".set _highEntrZBounds1,        _loopSurface_ZBounds0 + 0x8E\n"
	".globl _highEntrXInnBounds0\n"     ".set _highEntrXInnBounds0,     _loopSurface_ZBounds0 + 0x9A\n"
	".globl _highEntrXInnBounds1\n"     ".set _highEntrXInnBounds1,     _loopSurface_ZBounds0 + 0x9C\n"
	".globl _highEntrXOutBounds0\n"     ".set _highEntrXOutBounds0,     _loopSurface_ZBounds0 + 0xA8\n"
	".globl _highEntrXOutBounds1\n"     ".set _highEntrXOutBounds1,     _loopSurface_ZBounds0 + 0xAA\n"
);

/* ------------------------------------------------------------------ */
/* dseg 0x3F3C6 / 0x3F3C8 / 0x3F418 - preRender_sphere's scanline tables.     */
/*                                                                            */
/* word_3F3C6 (referenced as `ds:3C56h` in seg012.asm:10252, dseg base        */
/* 0x3B770) is the radius above which preRender_sphere stops using the        */
/* lookup tables and draws a 32-gon instead.  Its value in dseg.asm is 40,    */
/* which is exactly the number of entries in off_3F3C8.                       */
/*                                                                            */
/* off_3F3C8 (dseg.asm:16433..16472) is 40 near pointers, one per vertical    */
/* radius 0..39, into the flat byte block that starts at byte_3F418           */
/* (dseg.asm:16473..17252, 780 bytes).  Entry r is r bytes long and begins    */
/* at byte_3F418 + r*(r-1)/2 - verified against every one of the 40 `dw       */
/* offset byte_XXXXX` operands.  Byte i of entry r is the half-width of the   */
/* i-th scanline down from the top of the ellipse; the widths are already     */
/* aspect-corrected (entry 39 ends at 49 = round(39 * 1.25), the same 5/4     */
/* that seg012.asm:10241 applies to the polygon path).                        */
/* ------------------------------------------------------------------ */
const uint16_t word_3F3C6 = 40;

const uint8_t byte_3F418[780] = {
	/* r= 0: zero bytes long */
	/* r= 1 */ 1,
	/* r= 2 */ 2, 3,
	/* r= 3 */ 3, 4, 4,
	/* r= 4 */ 3, 4, 5, 5,
	/* r= 5 */ 4, 5, 6, 6, 6,
	/* r= 6 */ 4, 6, 6, 7, 7, 8,
	/* r= 7 */ 5, 6, 7, 8, 8, 9, 9,
	/* r= 8 */ 5, 7, 8, 9, 9, 10, 10, 10,
	/* r= 9 */ 5, 7, 8, 9, 10, 11, 11, 11, 11,
	/* r=10 */ 5, 8, 9, 10, 11, 11, 12, 12, 12, 13,
	/* r=11 */ 6, 8, 9, 11, 12, 12, 13, 13, 14, 14, 14,
	/* r=12 */ 6, 8, 10, 11, 12, 13, 14, 14, 15, 15, 15, 15,
	/* r=13 */ 6, 9, 10, 12, 13, 14, 14, 15, 15, 16, 16, 16, 16,
	/* r=14 */ 6, 9, 11, 12, 13, 14, 15, 16, 16, 17, 17, 17, 17, 18,
	/* r=15 */ 7, 9, 11, 13, 14, 15, 16, 17, 17, 18, 18, 18, 19, 19, 19,
	/* r=16 */ 7, 10, 12, 13, 15, 16, 17, 17, 18, 19, 19, 19, 20, 20, 20, 20,
	/* r=17 */ 7, 10, 12, 14, 15, 16, 17, 18, 19, 19, 20, 20, 21, 21, 21, 21, 21,
	/* r=18 */ 7, 10, 12, 14, 16, 17, 18, 19, 19, 20, 21, 21, 22, 22, 22, 22, 22, 23,
	/* r=19 */ 8, 11, 13, 15, 16, 17, 18, 19, 20, 21, 22, 22, 23, 23, 23, 23, 24, 24, 24,
	/* r=20 */ 8, 11, 13, 15, 17, 18, 19, 20, 21, 22, 22, 23, 23, 24, 24, 24, 25, 25, 25, 25,
	/* r=21 */ 8, 11, 14, 15, 17, 18, 20, 21, 22, 22, 23, 24, 24, 25, 25, 25, 26, 26, 26, 26, 26,
	/* r=22 */ 8, 11, 14, 16, 17, 19, 20, 21, 22, 23, 24, 24, 25, 26, 26, 26, 27, 27, 27, 27, 27, 28,
	/* r=23 */ 8, 12, 14, 16, 18, 19, 21, 22, 23, 24, 25, 25, 26, 26, 27, 27, 28, 28, 28, 29, 29, 29, 29,
	/* r=24 */ 9, 12, 15, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 27, 28, 28, 29, 29, 29, 30, 30, 30, 30, 30,
	/* r=25 */ 9, 12, 15, 17, 19, 20, 22, 23, 24, 25, 26, 27, 27, 28, 29, 29, 30, 30, 30, 31, 31, 31, 31, 31, 31,
	/* r=26 */ 9, 13, 15, 17, 19, 21, 22, 23, 25, 26, 27, 27, 28, 29, 29, 30, 30, 31, 31, 32, 32, 32, 32, 32, 32, 33,
	/* r=27 */ 9, 13, 15, 18, 20, 21, 23, 24, 25, 26, 27, 28, 29, 30, 30, 31, 31, 32, 32, 33, 33, 33, 33, 34, 34, 34, 34,
	/* r=28 */ 9, 13, 16, 18, 20, 22, 23, 24, 26, 27, 28, 29, 30, 30, 31, 32, 32, 33, 33, 34, 34, 34, 34, 35, 35, 35, 35, 35,
	/* r=29 */ 9, 13, 16, 18, 20, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 32, 33, 34, 34, 34, 35, 35, 35, 36, 36, 36, 36, 36, 36,
	/* r=30 */ 10, 13, 16, 19, 21, 23, 24, 25, 27, 28, 29, 30, 31, 32, 32, 33, 34, 34, 35, 35, 36, 36, 36, 37, 37, 37, 37, 37, 37, 38,
	/* r=31 */ 10, 14, 17, 19, 21, 23, 25, 26, 27, 29, 30, 31, 32, 32, 33, 34, 35, 35, 36, 36, 37, 37, 37, 38, 38, 38, 38, 39, 39, 39, 39,
	/* r=32 */ 10, 14, 17, 19, 21, 23, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35, 35, 36, 37, 37, 38, 38, 38, 39, 39, 39, 40, 40, 40, 40, 40, 40,
	/* r=33 */ 10, 14, 17, 20, 22, 24, 25, 27, 28, 30, 31, 32, 33, 34, 35, 35, 36, 37, 37, 38, 38, 39, 39, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41,
	/* r=34 */ 10, 14, 17, 20, 22, 24, 26, 27, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 38, 39, 39, 40, 40, 41, 41, 41, 42, 42, 42, 42, 42, 42, 42, 43,
	/* r=35 */ 10, 15, 18, 20, 23, 24, 26, 28, 29, 31, 32, 33, 34, 35, 36, 37, 38, 38, 39, 40, 40, 41, 41, 42, 42, 42, 43, 43, 43, 43, 43, 44, 44, 44, 44,
	/* r=36 */ 11, 15, 18, 21, 23, 25, 27, 28, 30, 31, 32, 34, 35, 36, 37, 37, 38, 39, 40, 40, 41, 41, 42, 42, 43, 43, 44, 44, 44, 44, 45, 45, 45, 45, 45, 45,
	/* r=37 */ 11, 15, 18, 21, 23, 25, 27, 29, 30, 32, 33, 34, 35, 36, 37, 38, 39, 40, 40, 41, 42, 42, 43, 43, 44, 44, 45, 45, 45, 45, 46, 46, 46, 46, 46, 46, 46,
	/* r=38 */ 11, 15, 18, 21, 24, 26, 27, 29, 31, 32, 33, 35, 36, 37, 38, 39, 40, 40, 41, 42, 42, 43, 44, 44, 45, 45, 45, 46, 46, 46, 47, 47, 47, 47, 47, 47, 47, 48,
	/* r=39 */ 11, 15, 19, 22, 24, 26, 28, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 43, 44, 44, 45, 46, 46, 46, 47, 47, 47, 48, 48, 48, 48, 48, 49, 49, 49, 49
};

const uint8_t* const off_3F3C8[40] = {
	byte_3F418 +   0, byte_3F418 +   0, byte_3F418 +   1, byte_3F418 +   3,
	byte_3F418 +   6, byte_3F418 +  10, byte_3F418 +  15, byte_3F418 +  21,
	byte_3F418 +  28, byte_3F418 +  36, byte_3F418 +  45, byte_3F418 +  55,
	byte_3F418 +  66, byte_3F418 +  78, byte_3F418 +  91, byte_3F418 + 105,
	byte_3F418 + 120, byte_3F418 + 136, byte_3F418 + 153, byte_3F418 + 171,
	byte_3F418 + 190, byte_3F418 + 210, byte_3F418 + 231, byte_3F418 + 253,
	byte_3F418 + 276, byte_3F418 + 300, byte_3F418 + 325, byte_3F418 + 351,
	byte_3F418 + 378, byte_3F418 + 406, byte_3F418 + 435, byte_3F418 + 465,
	byte_3F418 + 496, byte_3F418 + 528, byte_3F418 + 561, byte_3F418 + 595,
	byte_3F418 + 630, byte_3F418 + 666, byte_3F418 + 703, byte_3F418 + 741,
};

/* ------------------------------------------------------------------ */
/* sprite_clear_1_color -- native replacement for the video-driver           */
/* routine that fills the sprite1 clip window with a solid color.             */
/* Window convention (rblit.c): rows [sprite_top, sprite_height),             */
/* columns [sprite_left2, sprite_widthsum).                                   */
/*                                                                            */
/* [FIXED 2026-08-16] This clamped to 320x200 and used a stride of 320, both  */
/* hardcoded. At RFB_SCALE > 1 the framebuffer is larger than that, so the    */
/* sky and ground fills were clipped to a 320x200 corner and written with the */
/* wrong row length - which is why a scaled-up view showed a band of stale    */
/* pixels below the horizon. It is the framebuffer's own size that matters    */
/* here, not the original's screen size.                                      */
/* ------------------------------------------------------------------ */
extern struct SPRITE sprite1;     /* rblit.c */
extern uint8_t rfb_pixels[];      /* rblit.c */

void sprite_clear_1_color(uint8_t color)
{
	uint16_t y;
	uint16_t x0 = sprite1.sprite_left2;
	uint16_t x1 = sprite1.sprite_widthsum;
	uint16_t y1 = sprite1.sprite_height;
	if (x1 > RFB_VIEW_W) x1 = RFB_VIEW_W;
	if (y1 > RFB_VIEW_H) y1 = RFB_VIEW_H;
	for (y = sprite1.sprite_top; y < y1; y++) {
		if (x0 < x1)
			memset(&rfb_pixels[(uint32_t)y * RFB_VIEW_W + x0], color,
			       (size_t)(x1 - x0));
	}
}

/* dseg 0x4083C. Declared in externs.h and defined nowhere until Phase 7
 * needed it: the colour of the acceleration curve in the car picker.
 * restunts2 has it as `performGraphColor dw 0x0001`. */
int16_t performGraphColor = 1;
