#!/usr/bin/env python3
"""Transcribe the first bytes of the data segment into src/sim_faithful/sfdseg_head.c.

A TRKOBJINFO's si_cameraDataOffset is a near dseg offset, and 0 is a valid one:
it means dseg:0000. sub_18D60 dereferences it for tiles that have no shapeinfo
of their own, so the port needs those bytes to exist. See sfdseg_head.c.

Source is restunts2's dseg.asm, which opens with `word_3B770` at offset 0.
Parsing stops at the first structured initialiser (`RECTANGLE <...>`); that is
944 bytes in, far past anything sub_18D60 can reach, and the rest is zero-padded.
"""
import re, sys

SRC = 'reference/restunts2/src/asm/dseg.asm'
OUT = 'src/sim_faithful/sfdseg_head.c'
SIZE = 4096

def extract(path, limit):
    lines = open(path, errors='replace').read().split('\n')
    start = next(i for i, l in enumerate(lines) if l.startswith('word_3B770'))
    out = bytearray()
    for ln in lines[start:]:
        if len(out) >= limit:
            break
        s = ln.strip()
        if not s or s.startswith(';'):
            continue
        s = re.sub(r'\s+;.*$', '', s).strip()
        m = re.match(r'^(?:\S+\s+)?(db|dw|dd)\s+(.*)$', s)
        if not m:
            if re.match(r'^[A-Za-z_$@?][\w$@?]*\s*$', s):   # bare label
                continue
            break                                           # struct initialiser
        width = {'db': 1, 'dw': 2, 'dd': 4}[m.group(1)]
        rest = m.group(2)
        dup = re.match(r'^(\S+)\s+dup\s*\(\s*([^)]*)\s*\)$', rest)
        if dup:
            v = dup.group(2).strip()
            out += (0 if v == '?' else int(v, 0)).to_bytes(width, 'little') * int(dup.group(1), 0)
            continue
        for tok in re.findall(r'"[^"]*"|\'[^\']*\'|[^,]+', rest):
            tok = tok.strip()
            if not tok:
                continue
            if tok[0] in '"\'':
                out += tok[1:-1].encode('latin-1')
            elif tok == '?':
                out += b'\0' * width
            else:
                out += int(tok, 0).to_bytes(width, 'little')
    return out

data = extract(SRC, SIZE)
real = len(data)
if real < 64:
    sys.exit(f'bara {real} byte utvunna ur {SRC} - formatet har ändrats')
data += b'\0' * (SIZE - real)
rows = '\n'.join('\t' + ' '.join(f'0x{b:02X},' for b in data[i:i+16])
                 for i in range(0, SIZE, 16))
open(OUT, 'w').write(f'''/*
 * sfdseg_head.c - the first bytes of the data segment, as data.
 *
 * A TRKOBJINFO's si_cameraDataOffset is a near dseg offset. Tiles with no
 * shapeinfo of their own - element 0x00, the blank tile, being by far the most
 * common - carry offset 0, and in DOS that is a perfectly valid address: it is
 * dseg:0000, the start of the data segment. The original reads twelve bytes
 * from there, gets whatever happens to live at the front of dseg, and carries
 * on. Nothing faults, because nothing can.
 *
 * The port turned that offset into a C null pointer, so the same read
 * segfaulted the moment a blank tile entered the lookahead - which is to say,
 * on most of the tracks in the game.
 *
 * So dseg:0000 is reproduced here rather than substituted. The first {real}
 * bytes are the real contents, transcribed from restunts2's dseg.asm (which
 * opens with `word_3B770` at offset 0); the rest is zero padding so that no
 * offset in range can fault. sub_18D60 reads at most var_10*6+12 bytes in,
 * and var_10 is an 8-bit value, so {SIZE} covers every reachable read.
 *
 * Generated by tools/extract_dseg_head.py - do not edit by hand.
 */
#include <stdint.h>

const uint8_t sfdseg_head[{SIZE}] = {{
{rows}
}};
''')
print(f'{OUT}: {real} verkliga byte + nollor till {SIZE}')
